# Github action script for building linux executables of this project
# Copyright (C) 2022  VadVergasov as part of Plnguins

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: MacOS build

on:
  push:
    tags:
      - "*"
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - "**.md"
      - "LICENSE.txt"
      - "README.md"
      - ".github/**"
      - "!.github/workflows/macos-build.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE.txt"
      - "README.md"
      - ".github/**"
      - "!.github/workflows/macos-build.yml"

env:
  BUILD_TYPE: Debug
  QT_VERSION: "6.2.4"
  QT_DIR: ${{ github.workspace }}
  QT_TOOLS: "tools_ifw"
  BOOST_PLATFORM: 11
  BOOST_VERSION: "1.79.0"
  BOOST_DIR: ${{ github.workspace }}

jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64]
    steps:
      - name: Change to Release if tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "BUILD_TYPE=Release" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        name: Clone
        with:
          submodules: recursive
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ${{ env.QT_DIR }}/Qt
          key: ${{ runner.os }}-Qt-${{ env.QT_VERSION }}-${{ env.QT_DIR }}-${{ env.QT_TOOLS }}
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: ${{ env.BOOST_DIR }}/boost/boost
          key: ${{ runner.os }}-Boost-${{ env.BOOST_VERSION }}-${{ env.BOOST_DIR }}-${{ env.BOOST_PLATFORM }}
      - name: Install Qt
        uses: jurplel/install-qt-action@910f37ee23653fd4b243fe5c7f81ff26a8a6a64e
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: ${{ env.QT_VERSION }}
          dir: ${{ env.QT_DIR }}
          host: "mac"
          target: "desktop"
          setup-python: "false"
          tools: ${{ env.QT_TOOLS }}
          aqtversion: "==2.1.*"
          py7zrversion: ">=0.18.9"
      - name: Install boost
        id: install-boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        uses: MarkusJx/install-boost@v2.3.0
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: ${{ env.BOOST_PLATFORM }}
          toolset: clang
          boost_install_dir: ${{ env.BOOST_DIR }}
      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build -G Xcode \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DBoost_INCLUDE_DIR=${{ env.BOOST_DIR }}/boost/boost/include \
          -DBoost_LIBRARY_DIRS=${{ env.BOOST_DIR }}/boost/boost/lib \
          -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 \
          -DOPENSSL_LIBRARIES=/usr/local/opt/openssl@1.1/lib
      - name: List targets
        run: xcodebuild -project ${{ github.workspace }}/build/CRM.xcodeproj -list
      - uses: actions/upload-artifact@v3
        name: Upload bundle
        with:
          name: MacOS
          path: ${{ github.workspace }}/build/bin/CRM.dmg
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: macos
    name: Create\Update release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: MacOS
          path: ${{ github.workspace }}/MacOS
      - name: Get branch name
        uses: EthanSK/git-branch-name-action@v1
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "${{ github.workspace }}/MacOS/CRM.dmg"
          name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: ${{ env.GIT_BRANCH_NAME == 'master' }}
